from event_extraction_.subject_extraction import *



print(find_sub_for_verb(nlp("my husband's parents flew out to meet my family when we got married in my hometown , so that was great "),"married"))
print(find_sub_for_verb(nlp("i've got a really bad headache and my stomach hurts"),"hurts"))
print(find_sub_for_verb(nlp("people divorced every year"),"divorced"))
print(find_sub_for_verb(nlp("karla's sun have an exam"),"have"))
print(find_sub_for_verb(nlp("my brother have an exam"),"have"))
print(find_sub_for_verb(nlp("sam and george have an exam"),"have"))
print(find_sub_for_verb(nlp("i'm interviewed on montana public radio today about my life"),"interviewed"))
print(find_sub_for_verb(nlp("i heard she and george and sam has passed the bar exam and married recently "),"married"))
print(find_sub_for_verb(nlp("george went for a job interview earlier and got the job "),"got"))
print(findSubs_for_actionEvents(nlp("george went for a job interview earlier and got the job"),verb_with_prepo))
print(findSubs_for_nounsEvents(nlp("george went for a job interview earlier and got the job"),nouns))
print(find_sub_for_verb(nlp("today my wife and i celebrate our 1st wedding anniversary "),"celebrate"))
print(find_sub_for_verb(nlp("i heard she has passed the bar exam and married recently "),"passed"))
print(find_sub_for_verb(nlp("joy's father died and he is very depressed"),"died"))
print(find_sub_for_verb(nlp("Marla will have an surgery next week "),"have"))
print(find_sub_for_verb(nlp("nathan and i married last week "),"married"))
print(find_sub_for_verb(nlp("tomas divorced katty and take her alone ."),"divorced"))
print(find_sub_for_verb(nlp("you and me will married this month ."),"married"))
print(findSubs_for_nounsEvents(nlp("Marla will have an surgery next week "),nouns))
print(findSubs_for_verbEvents(nlp("i've got a really bad headache and my stomach and george hurts"),verbs_without_need_objects))
print(findSubs_for_nounsEvents(nlp("(you are invited to my wedding"),nouns))
print(findSubs_for_verbEvents(nlp("i heard your son recently graduated"),verbs_without_need_objects))
print(findSubs_for_verbEvents(nlp("my husband flew out to meet my family when we got married in my hometown "),verbs_without_need_objects))
print(findSubs_for_verbEvents(nlp("defending my thesis was great"),verbs_with_objects))
print(findSubs_for_verbEvents(nlp("karla's sun passed the exam in 1999"),verbs_with_objects))
print(findSubs_for_verbEvents(nlp("do you want to go out to celebrate my good news"),verbs_with_objects))
print(findSubs_for_verbEvents(nlp("should probably let u all know that george and i are now engaged"),verbs_without_need_objects))
print(findSubs_for_verbEvents(nlp("my paper and george was published in 1999"),verbs_with_objects))
print(findSubs_for_verbEvents(nlp("the studio interviewed me last year"),verbs_without_need_objects))
print(findSubs_for_verbEvents(nlp("the studio interviewed my boss last year"),verbs_without_need_objects))
print(findSubs_for_direct_relation(nlp("my wedding was last week"),noun_direct_relation))
print(findSubs_for_adjectiveEvents(nlp("i'm very sick and i have a fever"),adjectives))
print(findSubs_for_nounsEvents(nlp("george will have an surgery next week "),nouns))
print(findSubs_for_nounsEvents(nlp("kareem get to finish his masters "),nouns))
print(findSubs_for_actionEvents(nlp("we are moving to palmera last week"),verb_with_prepo))

